import Link from "next/link";
import storyData from "../stories";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/navigation";
import { Pagination, Navigation } from "swiper";
import Head from "next/head";

export default function SuccessStories() {
  const data = storyData;
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="success_stories">
        <Row>
          <Col>
            <h1>Success Stories</h1>
            <h2 className="sub_text">
              Explore how our AI solutions have helped businesses and
              governments increase work efficiency, optimize processes, minimize
              risks, and get insights from their data.
            </h2>
          </Col>
        </Row>
        <Row>
          <Col>
            {" "}
            <Swiper
              slidesPerView={1}
              spaceBetween={0}
              pagination={{
                type: "progressbar",
              }}
              navigation={true}
              modules={[Pagination, Navigation]}
              breakpoints={{
                768: {
                  slidesPerView: 2,
                },
                1024: {
                  slidesPerView: 3,
                },
              }}
              className="mySwiper"
            >
              {data.map((story) => (
                <SwiperSlide key={story.Id}>
                  <div className="story_sec">
                    <Link href={`/story/${story.Slug}`}>
                      <div className="story_tile">
                        <h3>{story.Title}</h3>
                        <p>{story.Text}</p>
                      </div>
                    </Link>
                  </div>
                </SwiperSlide>
              ))}
            </Swiper>
          </Col>
        </Row>
      </Container>
    </>
  );
}
